---
copy_nonce: true
certificate_authorities:
  rcv_spec_ca:
    ca_cert:
      cert: /app/ca/root.crt
      key: /app/ca/root.key
    ocsp_start_skew_seconds: 3600
    ocsp_validity_hours: 168
    crl_list_file: /app/ca/rcv_spec_list.txt
    crl_number_file: /app/ca/rcv_spec_crlnumber.txt
    crl_validity_hours: 87600
    crl_md: SHA1
    profiles:
      good:
        authority_info_access:
          :ocsp_location:
          -  :type: URI
             :value: http://cert-validator-test.herokuapp.com/ocsp
        crl_distribution_points:
          :value:
          -  :type: URI
             :value: http://cert-validator-test.herokuapp.com/revoked.crl
      crl_only:
        crl_distribution_points:
          :value:
          -  :type: URI
             :value: http://cert-validator-test.herokuapp.com/revoked.crl
      ocsp_only:
        authority_info_access:
          :ocsp_location:
          -  :type: URI
             :value: http://cert-validator-test.herokuapp.com/ocsp
certwriter:
  path: /app/ca
